### PR TITLE
#4 Added license and license headers back to project

### PR DESCRIPTION
**Pull request by ToxicBakery**
Updated to match the original source project https://github.com/ToxicBakery/ViewPagerTransforms

### CODE REVIEW

**Comment by AndreasBackx** [comment]
+1

**Comment by langerhans** [comment]
ezgif-537721928

**Comment by EddieRingle** [comment]
:+1:

**Comment by geftimov** [comment]
Hmmm,
I did not steal the library from you.
I added you to the Readme.

I needed just more complete documentation of how the transformers work.
Also have created 2-3 additional transformers so to use them I have added the library to maven.

If you want I can delete this repository, no problem with that.

**Comment by geftimov** [comment]
Ok I am deleting the repository after 18 minutes.
If someone has something to say about it , now is the time.

**Comment by ToxicBakery** [comment]
No one said you stole anything, you removed the licensing which is the only problem.

**Comment by geftimov** [comment]
That is not true, I have not delete anything.
This is an fork from https://github.com/daimajia/ViewPagerTransforms
You check the source code there.

I have even write it in the Readme that is a fork.

**Comment by langerhans** [comment]
LICENSE was deleted in 83680cfd9349b2899253ac9dca0ff3efa9680c9e

**Comment by geftimov** [comment]
This is auto generated LICENSE , 
see the names in the file
https://github.com/geftimov/android-viewpager-transformers/blob/22aac66a5e7a26c4a79560a296b631e37db579a5/LICENSE

**Comment by langerhans** [comment]
The file is in the exact repository you "forked" from, the magically vanished.

**Comment by geftimov** [comment]
Interesting there is the exact same auto generated file LICENSE in
https://github.com/daimajia/ViewPagerTransforms
Strange, but however I have not deleted the javadoc from the java files ,
and this LICENSE is empty, it does not contain a name or anything.

**Comment by geftimov** [comment]
Does everyone think it is my fault and I have delete the license info in purpose?
:+1: if you think it is my fault.

**Comment by ToxicBakery** [comment]
Please just accept the PR and everyone can move on with their life. Neither this issue nor the PR accuses you of anything it simply updates the project to match the original in regards to licensing.

**Comment by geftimov** [comment]
@ToxicBakery 
Ok merged , can you tell me why did you make this PR , but not in 
https://github.com/daimajia/ViewPagerTransforms ?

**Comment by ToxicBakery** [comment]
The lack of the root license, the fact the repo was intentionally or unintentionally an unlinked fork from the source repository, the dropping of all repository commit history which essentially removes attribution to contributors, and the fact the package name was change so that it may be uploaded to maven despite the source repo already existing on maven. If the goal was to put the pre v13 support onto maven, the code package name did not need to change to accomplish that nor did any of the other changes.

**Pull request merged**
